services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40000:40000"
      - "8084:8080"
    env_file:
      - path: ./default.env
        required: true
      - path: ./override.env
        required: false
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/postgres
    environment:
      - POSTGRES_USER=caker-db-user
      - POSTGRES_PASSWORD=veryComplicatedPassword5720
      - POSTGRES_DB=caker-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "caker-db", "-U", "caker-db-user"]
      start_period: 5s
      start_interval: 1s

  ftp:
    image: docker.io/markhobson/vsftpd
    volumes:
      - ./assets:/home/vsftpd
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppass
      - PASV_ENABLE=NO
      - LOCAL_UMASK=022
    ports:
      - "4021:21"
      - "30000-30009:30000-30009"

  swagger:
    image: docker.io/swaggerapi/swagger-ui
    ports:
      - "8085:8080"
    environment:
      - API_URL=http://localhost:40000/swagger/v1/swagger.json
    depends_on:
      - server

  adminer:
    image: docker.io/adminer
    ports:
      - "5431:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=db
      - ADMINER_DEFAULT_DB_USERNAME=caker-db-user
      - ADMINER_DEFAULT_DB_PASSWORD=veryComplicatedPassword5720
      - ADMINER_DEFAULT_DB_NAME=caker-db

volumes:
  db-data:
