FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine

WORKDIR /app

COPY . .

RUN dotnet tool install --global dotnet-ef

ENV PATH="$PATH:/root/.dotnet/tools"

CMD ["dotnet", "ef", "database", "update", "--connection", "Host=db;Port=5432;Database=caker-db;Username=caker-db-user;Password=veryComplicatedPassword5720;"]