// <auto-generated />
using System;
using Caker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caker.Migrations
{
    [DbContext(typeof(CakerDbContext))]
    [Migration("20250423211155_DiametersTastes")]
    partial class DiametersTastes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caker.Models.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("ConfectionerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "confectioner_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Diameter")
                        .HasColumnType("double precision");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("ReqTime")
                        .HasColumnType("interval")
                        .HasAnnotation("Relational:JsonPropertyName", "req_time");

                    b.Property<string>("Taste")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConfectionerId");

                    b.ToTable("Cakes");
                });

            modelBuilder.Entity("Caker.Models.Confectioner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxDiameter")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "max_diameter");

                    b.Property<double>("MinDiameter")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "min_diameter");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<string[]>("Tastes")
                        .HasColumnType("text[]");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Confectioners");
                });

            modelBuilder.Entity("Caker.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Caker.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CakeId")
                        .HasColumnType("integer");

                    b.Property<int>("ConfectionerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "confectioner_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CakeId");

                    b.HasIndex("ConfectionerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Caker.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "from_id");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("ToId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "to_id");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Messages");

                    b.HasAnnotation("Relational:JsonPropertyName", "messages_to");
                });

            modelBuilder.Entity("Caker.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CakeId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "cake_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "creation_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "customer_id");

                    b.Property<TimeSpan>("Eta")
                        .HasColumnType("interval");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "order_status");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "payment_status");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CakeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Caker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "phone_number");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Caker.Models.Cake", b =>
                {
                    b.HasOne("Caker.Models.Confectioner", "Confectioner")
                        .WithMany("Cakes")
                        .HasForeignKey("ConfectionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confectioner");
                });

            modelBuilder.Entity("Caker.Models.Confectioner", b =>
                {
                    b.HasOne("Caker.Models.User", "User")
                        .WithOne("Confectioner")
                        .HasForeignKey("Caker.Models.Confectioner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caker.Models.Customer", b =>
                {
                    b.HasOne("Caker.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Caker.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caker.Models.Feedback", b =>
                {
                    b.HasOne("Caker.Models.Cake", "Cake")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caker.Models.Confectioner", "Confectioner")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ConfectionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caker.Models.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");

                    b.Navigation("Confectioner");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Caker.Models.Message", b =>
                {
                    b.HasOne("Caker.Models.User", "From")
                        .WithMany("MessagesFrom")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caker.Models.User", "To")
                        .WithMany("MessagesTo")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Caker.Models.Order", b =>
                {
                    b.HasOne("Caker.Models.Cake", "Cake")
                        .WithMany("Orders")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caker.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Caker.Models.Cake", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Caker.Models.Confectioner", b =>
                {
                    b.Navigation("Cakes");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Caker.Models.Customer", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Caker.Models.User", b =>
                {
                    b.Navigation("Confectioner");

                    b.Navigation("Customer");

                    b.Navigation("MessagesFrom");

                    b.Navigation("MessagesTo");
                });
#pragma warning restore 612, 618
        }
    }
}
